### ISSUE TITLE
Reports failing with more than two runs

### ISSUE THREAD

**Issue by ckoppelman** [phelipetls/reportforce#5]
I have a report that returns 8007 records.

As the package stands, it will add one filter for the `id_column`.  There are two issues with this.

First, it seems that Salesforce understands filters better when the values are quoted.

Second, there is a limit in the length of each filter value.  Salesforce throws a BAD_REQUEST error if you have a filter that's too long.

One more constraint: "A report can't have more than 20 filters".

I'm not entirely sure how to accommodate the two constraints and still return all rows of an arbitrarily large report, but I do have a patch that at least gets you to 8007.

Haven't tested it, but quotation marks will need to be escaped in that `map` lambda, and many value types should not be quoted.  I was only testing with Id/Lookup fields

```diff
diff --git a/reportforce/helpers/generators.py b/reportforce/helpers/generators.py
index ff5bb22..566102f 100644
+++ a/reportforce/helpers/generators.py
--- b/reportforce/helpers/generators.py
@@ -31,13 +31,11 @@ def report_generator(get_report):
         df = pd.DataFrame(report_cells, index=indices, columns=columns)
         yield df
 
-        if id_column:
-            already_seen = ",".join(df[id_column].values)
-            set_filters([(id_column, "!=", already_seen)], metadata)
-
-            increment_logical_filter(metadata)
+        if id_column and len(df[id_column]):
+            inc = 2000
+            for ix in range(0, len(df[id_column]), inc):
+                already_seen = ",".join(map(lambda val: '"%s"' % val,
+                                            df[id_column][(ix*inc):inc+(ix*inc)]))
+                set_filters([(id_column, "!=", already_seen)], metadata)
+                increment_logical_filter(metadata)
 
             while not report["allData"]:
                 # getting what is needed to build the dataframe
@@ -49,10 +47,8 @@ def report_generator(get_report):
                 yield df
 
                 # filtering out already seen values for the next report
-                already_seen += ",".join(df[id_column].values)
-                update_filter(-1, "value", already_seen, metadata)
+                already_seen = ",".join(map(lambda val: '"%s"' % val,
+                                            df[id_column][(ix*inc):inc+(ix*inc)]))
+                set_filters([(id_column, "!=", already_seen)], metadata)
+                increment_logical_filter(metadata)
 
     @functools.wraps(get_report)
     def concat(*args, **kwargs):
```

**Comment by ckoppelman** [comment]
This is obviously poorly-written, by the way.  It does work, but the common logic should be extracted.

**Comment by phelipetls** [comment]
Thanks for this. I'll look carefully into it.

I was not aware of the limit to the filter value length.

I think one way to work around this is to sort by `id_column` (ascending orgder) and, in each iteration, filter for values only greater than the last value. 

Anyway, I'll see what I can do. I'll contact you if I have trouble to understand the code.

**Comment by ckoppelman** [comment]
This would work for my current use case, but I can easily imagine others who have reports sorted in a business-defined order

**Comment by phelipetls** [comment]
Could you explain why you did that for loop to get the already seen `id_column` values? In my understanding, no loop is necessary because `df` is always going to have at maximum 2000 rows, so it is only necessary to join those?

Yeah, I see... perhaps it would be better to do this depending on the data type? If it's numeric, date, currency etc. we could sort it, otherwise just concatenate all previously seen values.

**Comment by ckoppelman** [comment]
You know the insides of this code more than I do. I was just trying to get my report to work. It may be overworked

**Comment by ckoppelman** [comment]
The easiest thing to order by is whatever the date is, but when you talk about grouped reports, it throws everything off. It might be reasonable to say that there's a limit of `2000*(21-num_other_filters)`

**Comment by ckoppelman** [comment]
Looks like stack exchange users have two solutions. 

Most sort by unique id and use a greater than filter. This doesn't work that well for aggregated reports.  Eg, there are 5000 contracts in New York or Hyderabad and you group by city, the min, max, avg and count summaries are just wrong. 

A small minority effectively use a headless browser to hit the web app's export url.

**Comment by phelipetls** [comment]
This is definitely more complicated. I'll work on it through the week. I'm also refactoring the code to be more reusable and testable as I go along, so I may not deliver it so soon.

Just one comment though, I think there's no need to escape the quotes because `requests` already does that for us, IIRC. Also, what happened when the values were not enclosed by quotes? An error was thrown?

Thanks for all the help in making the library better! I appreciate it.

**Comment by ckoppelman** [comment]
Without quotes, it failed on the second query with BAD_REQUEST. With quotes, it failed on the third. Not sure why. 

Thank you for putting time and effort into maintaining this. I know that writing software's a lot easier than writing an open source library and the latter is often underappreciated. Thanks for creating and maintaining something useful to folks who aren't just doing what you do! It's a challenge and I appreciate the leg up to the community!

**Comment by phelipetls** [comment]
My intuition says it must be something else that caused the problem... I'll see what I can find out.

You're welcome! It's been a great experience so far!

**Comment by ckoppelman** [comment]
By "escaping quotes", by the way, I didn't mean escaping for HTTP or XML - I meant escaping for Salesforce.

NB: My knowledge of all this comes from the web app and not the API, so rules may be different for the API.

If you're trying to run a report within Salesforce and you have a filter value that has a comma in it (e.g., `equals` a picklist value of `Chocolate, No Raspberries`), the filter value needs to be quoted (`"Chocolate, No Raspberries"`).  Otherwise Saleforce Reports interprets the filter as `equals Chocolate OR equals No Raspberries`.

So if there are any internal commas in the filter, each value needs to be quoted.  However, if someone has decided that a picklist value should have a quotation mark in it, and they want to filter on that (e.g., `Not "Chocolate"`), I honestly don't know what happens.  I assume we'd need to solve that problem, though, before it happens.

**Comment by phelipetls** [comment]
I'm currently trying to implement the approach of narrowing down the report by sorting or by filtering the already seen values.

At first I thought it would be wise to sort if the column was "sortable", e.g., of data type id, int etc., anything that looked like a primary key. But the column data type isn't always accurate...

I was looking at the documentation and it doesn't seem to have any field like 'isPrimaryKey'.

So I thought that it could be reasonable to sort the column if all 2000 first observations were unique. I think it is a reasonable sample... and anyway I expect the user to provide something that could serve as a primary key.

**Comment by phelipetls** [comment]
I understand the comma problem now. I'm just thinking though that surrounding every value with quotes will worse the limitation on the filter value length... One solution could be to just surround it if there is a comma in it. Kinda like `[f'{v}' if v.find(',') > 0 else v for v in df[id_column]]`, but I'd worried it would worse the performance or if it would be negligible... I'll implement it and do a profiling.

**Comment by phelipetls** [comment]
Hey, sorry for the delay on this. I'm actually refactoring the whole package... I just didn't like a lot of the decisions I have made and it ended cumbersome to maintain. I'm doing a more OOP approach, so everything is more organized.

I think your solution is the right one. In order to avoid the filter length limit, just add another filter. I'll do that as well. Thanks.
