### ISSUE TITLE
is there any option for a conda installation?

### ISSUE THREAD

**Issue by robsomething** [phelipetls/reportforce#7]
Hi there, I like the idea for the package and want to try it out.  My team uses the anaconda environment to keep us uniform.  Pip install may break things for us.  Is there a conda install option?

**Comment by phelipetls** [comment]
Hey, glad the package seems useful.

I'm not familiar with conda to be honest. Doesn't `conda install reportforce` works out of the box? If it doesn't, do I have to upload the package in a conda-specific package index?
